name: logbook_core
description: Shared code for app and CLI.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  get_it: ^7.2.0
  path: ^1.8.1
  system: ^1.0.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
