name: logbook_cli
description: Provides access on miscellaneous logbook functionality.
version: 0.1.0

environment:
  sdk: '>=2.17.1 <3.0.0'

executables:
  logbook: logbook_cli

dependencies:
  args: ^2.3.1
  logbook_core:
    path: ../logbook_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
