name: logbook_app
description: Note taking utility for software engineers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_markdown: ^0.6.10+2
  logbook_core:
#     path: ../logbook_core
    git:
      url: https://github.com/experimental-software/logbook.git
      path: packages/logbook_core
      ref: master
  test: ^1.21.1
  url_launcher: ^6.1.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
