name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Setup build dependencies
        run: sudo snap install snapcraft --classic && sudo snap install lxd

      - name: Initialize LXD
        uses: bonddim/action-lxd-init@v1

      - name: Compile Snap
        run: cd packages/logbook_app && snapcraft --use-lxd

      - name: Upload Snap to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "packages/logbook_app/*.snap"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
